name: jdr_maker
description: Application créatrice de JDR
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.3.2"

# Mise à jour des dépendances avec
# flutter pub upgrade --major-versions
#
# Installation d'une dépendance
# flutter pub add nom_dependance
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Rooting
  provider: ^6.0.3
  # Firebase Desktop
  firedart: ^0.9.0+1
  # Firebase Android
  cloud_firestore: ^4.0.1
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.1
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/img/
    - assets/json/
    - assets/music/
    - assets/sound/
